# This is the development file
version: "3.7"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: development-stage
    volumes:
      # Mount src dir into container
      - ./src:/app/src
    ports:
      # Run dev server on host port 8090
      - "8090:8090"
    restart: "no"

