# This is the development file
version: "3.7"

services:

  frontend:
    build:
      context: .
      target: 'develop-stage'
    volumes:
      - ./src:/app/src
    ports:
      - "8080:8080"
    environment:
      NODE_ENV: development
      CHOKIDAR_USEPOLLING: "true"
    restart: "no"
    command: /bin/sh -c "npm run serve"
    # logging:
    #   driver: none
